pluginGroup=net.tagpad.cmakemux
pluginName=CMake Mux
pluginRepositoryUrl=https://github.com/hoxi/cmake-mux
pluginVersion=2026.1
pluginSinceBuild=252
platformType=CL
#platformVersion=LATEST-EAP-SNAPSHOT
platformVersion=2026.1
platformBundledPlugins=com.intellij.clion,com.intellij.clion.cmake
gradleVersion=9.4.1
kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.jvmargs=-Xms1g -Xmx2g -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
